import Head from "next/head"
import Link from "next/link"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>HomePage</h1>
      <p className={styles.text}>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
        blanditiis quae dolorum perferendis dolorem molestiae error? Rem commodi
        ratione cumque nemo enim? Perspiciatis quaerat eaque, odio hic, eius
        rem, non sequi cumque quos error doloribus ab fugit sint ipsa. Nostrum
        rerum omnis consequatur nulla dicta eius veniam voluptatem. Recusandae
        consequatur doloribus ad inventore eos aperiam atque praesentium
        laborum, harum, debitis sequi, eum voluptatem dicta reprehenderit!
        Soluta quis sit, veniam voluptatibus ducimus animi, est tempora sunt
        aliquam repellendus in voluptate qui sequi praesentium eaque, minus modi
        illum temporibus odit earum eum aliquid! Facere necessitatibus accusamus
        est iure labore obcaecati accusantium inventore!
      </p>
      <p className={styles.text}>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
        blanditiis quae dolorum perferendis dolorem molestiae error? Rem commodi
        ratione cumque nemo enim? Perspiciatis quaerat eaque, odio hic, eius
        rem, non sequi cumque quos error doloribus ab fugit sint ipsa. Nostrum
        rerum omnis consequatur nulla dicta eius veniam voluptatem. Recusandae
        consequatur doloribus ad inventore eos aperiam atque praesentium
        laborum, harum, debitis sequi, eum voluptatem dicta reprehenderit!
        Soluta quis sit, veniam voluptatibus ducimus animi, est tempora sunt
        aliquam repellendus in voluptate qui sequi praesentium eaque, minus modi
        illum temporibus odit earum eum aliquid! Facere necessitatibus accusamus
        est iure labore obcaecati accusantium inventore!
      </p>
      <Link href="/users" className={styles.btn}>
        See Fang Fang List
      </Link>
    </>
  )
}
